name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform -chdir=envs/prod init -input=false

      - name: Terraform Validate
        run: terraform -chdir=envs/prod validate

      - name: Terraform Plan
        run: terraform -chdir=envs/prod plan -out=tfplan -input=false

      - name: Terraform Apply (only on main)
        if: ${{ github.ref_name == 'main' }}
        run: terraform -chdir=envs/prod apply -auto-approve -input=false tfplan
