name: Terraform Plan & Apply (prod)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      AWS_REGION: ap-south-1
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=envs/prod init -input=false

      - name: Terraform Validate
        run: terraform -chdir=envs/prod validate

      - name: Terraform Plan
        run: terraform -chdir=envs/prod plan -out=tfplan -input=false

      - name: Upload Plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-prod
          path: envs/prod/tfplan

      - name: Terraform Apply (only on main)
        if: ${{ github.ref_name == 'main' }}
        run: terraform -chdir=envs/prod apply -input=false -auto-approve tfplan
